remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: MatPy
description: A comprehensive Python library for vector and matrix operations
show_downloads: true
github:
  repository_url: https://github.com/njryan-boou/matpy
  zip_url: https://github.com/njryan-boou/matpy/zipball/main
  tar_url: https://github.com/njryan-boou/matpy/tarball/main
